package cn.ziroom.system.domain;

import java.util.ArrayList;
import java.util.List;

import cn.common.service.GeneralCriteria;

public class Function extends GeneralCriteria {

	private static final long serialVersionUID = 7621653219730109991L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.function_id
     *
     * @mbggenerated Mon Dec 26 10:31:50 CST 2011
     */
    private Integer functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.function_name
     *
     * @mbggenerated Mon Dec 26 10:31:50 CST 2011
     */
    private String functionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.function_code
     *
     * @mbggenerated Mon Dec 26 10:31:50 CST 2011
     */
    private String functionCode;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_function.parent_id
     *
     * @mbggenerated Mon Dec 26 10:31:50 CST 2011
     */
    private Integer parentId;
    
    private Integer id;
    
    private String text;
    
    private boolean checked;
    
    private List<Function> children = new ArrayList<Function>();

    public Integer getFunctionId() {
        return functionId;
    }

    public void setFunctionId(Integer functionId) {
        this.functionId = functionId;
    }

    public String getFunctionName() {
        return functionName;
    }

    public void setFunctionName(String functionName) {
        this.functionName = functionName == null ? null : functionName.trim();
    }

    public String getFunctionCode() {
        return functionCode;
    }

    public void setFunctionCode(String functionCode) {
        this.functionCode = functionCode == null ? null : functionCode.trim();
    }

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public List<Function> getChildren() {
		return children;
	}

	public void setChildren(List<Function> children) {
		this.children = children;
	}

	public boolean isChecked() {
		return checked;
	}

	public void setChecked(boolean checked) {
		this.checked = checked;
	}
}