package cn.ziroom.contract.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Contract implements java.io.Serializable {

	private static final long serialVersionUID = 3008871818379299616L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.id
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.cust_code
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String custCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.house_code
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String houseCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.room_code
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String roomCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.contract_code
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String contractCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.security_code
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String securityCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.cycle
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String cycle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.vacancy
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String vacancy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.sign_date
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private Date signDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.effect_date
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private Date effectDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.stop_date
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private Date stopDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.price
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private BigDecimal price;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.store_num
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String storeNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.store_name
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String storeName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.business_name
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String businessName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.area_name
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String areaName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.store_leader_code
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String storeLeaderCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.store_leader_name
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String storeLeaderName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.store_agent_code
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String storeAgentCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.store_agent_name
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String storeAgentName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.agent_code
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String agentCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.house_product
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String houseProduct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.rental
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String rental;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.payment
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String payment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.contract_state
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String contractState;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_contract.contract_type
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String contractType;

	private Integer sysContractId;

	private Integer sysRoomId;

	private Integer sysHouseId;

	private Integer sysCustId;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCustCode() {
		return custCode;
	}

	public void setCustCode(String custCode) {
		this.custCode = custCode == null ? null : custCode.trim();
	}

	public String getHouseCode() {
		return houseCode;
	}

	public void setHouseCode(String houseCode) {
		this.houseCode = houseCode == null ? null : houseCode.trim();
	}

	public String getRoomCode() {
		return roomCode;
	}

	public void setRoomCode(String roomCode) {
		this.roomCode = roomCode == null ? null : roomCode.trim();
	}

	public String getContractCode() {
		return contractCode;
	}

	public void setContractCode(String contractCode) {
		this.contractCode = contractCode == null ? null : contractCode.trim();
	}

	public String getSecurityCode() {
		return securityCode;
	}

	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode == null ? null : securityCode.trim();
	}

	public String getCycle() {
		return cycle;
	}

	public void setCycle(String cycle) {
		this.cycle = cycle == null ? null : cycle.trim();
	}

	public String getVacancy() {
		return vacancy;
	}

	public void setVacancy(String vacancy) {
		this.vacancy = vacancy == null ? null : vacancy.trim();
	}

	public Date getSignDate() {
		return signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public Date getEffectDate() {
		return effectDate;
	}

	public void setEffectDate(Date effectDate) {
		this.effectDate = effectDate;
	}

	public Date getStopDate() {
		return stopDate;
	}

	public void setStopDate(Date stopDate) {
		this.stopDate = stopDate;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getStoreNum() {
		return storeNum;
	}

	public void setStoreNum(String storeNum) {
		this.storeNum = storeNum == null ? null : storeNum.trim();
	}

	public String getStoreName() {
		return storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName == null ? null : storeName.trim();
	}

	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName == null ? null : businessName.trim();
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName == null ? null : areaName.trim();
	}

	public String getStoreLeaderCode() {
		return storeLeaderCode;
	}

	public void setStoreLeaderCode(String storeLeaderCode) {
		this.storeLeaderCode = storeLeaderCode == null ? null : storeLeaderCode.trim();
	}

	public String getStoreLeaderName() {
		return storeLeaderName;
	}

	public void setStoreLeaderName(String storeLeaderName) {
		this.storeLeaderName = storeLeaderName == null ? null : storeLeaderName.trim();
	}

	public String getStoreAgentCode() {
		return storeAgentCode;
	}

	public void setStoreAgentCode(String storeAgentCode) {
		this.storeAgentCode = storeAgentCode == null ? null : storeAgentCode.trim();
	}

	public String getStoreAgentName() {
		return storeAgentName;
	}

	public void setStoreAgentName(String storeAgentName) {
		this.storeAgentName = storeAgentName == null ? null : storeAgentName.trim();
	}

	public String getAgentCode() {
		return agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode == null ? null : agentCode.trim();
	}

	public String getHouseProduct() {
		return houseProduct;
	}

	public void setHouseProduct(String houseProduct) {
		this.houseProduct = houseProduct == null ? null : houseProduct.trim();
	}

	public String getRental() {
		return rental;
	}

	public void setRental(String rental) {
		this.rental = rental == null ? null : rental.trim();
	}

	public String getPayment() {
		return payment;
	}

	public void setPayment(String payment) {
		this.payment = payment == null ? null : payment.trim();
	}

	public String getContractState() {
		return contractState;
	}

	public void setContractState(String contractState) {
		this.contractState = contractState == null ? null : contractState.trim();
	}

	public String getContractType() {
		return contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType == null ? null : contractType.trim();
	}

	public Integer getSysContractId() {
		return sysContractId;
	}

	public void setSysContractId(Integer sysContractId) {
		this.sysContractId = sysContractId;
	}

	public Integer getSysRoomId() {
		return sysRoomId;
	}

	public void setSysRoomId(Integer sysRoomId) {
		this.sysRoomId = sysRoomId;
	}

	public Integer getSysHouseId() {
		return sysHouseId;
	}

	public void setSysHouseId(Integer sysHouseId) {
		this.sysHouseId = sysHouseId;
	}

	public Integer getSysCustId() {
		return sysCustId;
	}

	public void setSysCustId(Integer sysCustId) {
		this.sysCustId = sysCustId;
	}
}