package cn.ziroom.contract.domain;

import java.util.Date;

public class Customer implements java.io.Serializable {

	private static final long serialVersionUID = -6956378336990379454L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.id
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.cust_name
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String custName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.cust_code
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String custCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.phone
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.sex
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.birth_place
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String birthPlace;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.birth
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private Date birth;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.email
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.certificate_type
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String certificateType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.cert_num
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String certNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.origin
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String origin;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.degree
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String degree;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.marriage
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String marriage;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.professional
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String professional;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.nationality
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String nationality;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.work_unit
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String workUnit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.address
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.national
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String national;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.cust_status
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String custStatus;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_customer.cust_type
	 * 
	 * @mbggenerated Mon Dec 12 15:45:05 CST 2011
	 */
	private String custType;
	
	private Integer sysCustId;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCustName() {
		return custName;
	}

	public void setCustName(String custName) {
		this.custName = custName == null ? null : custName.trim();
	}

	public String getCustCode() {
		return custCode;
	}

	public void setCustCode(String custCode) {
		this.custCode = custCode == null ? null : custCode.trim();
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	public String getBirthPlace() {
		return birthPlace;
	}

	public void setBirthPlace(String birthPlace) {
		this.birthPlace = birthPlace == null ? null : birthPlace.trim();
	}

	public Date getBirth() {
		return birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	public String getCertificateType() {
		return certificateType;
	}

	public void setCertificateType(String certificateType) {
		this.certificateType = certificateType == null ? null : certificateType.trim();
	}

	public String getCertNum() {
		return certNum;
	}

	public void setCertNum(String certNum) {
		this.certNum = certNum == null ? null : certNum.trim();
	}

	public String getOrigin() {
		return origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin == null ? null : origin.trim();
	}

	public String getDegree() {
		return degree;
	}

	public void setDegree(String degree) {
		this.degree = degree == null ? null : degree.trim();
	}

	public String getMarriage() {
		return marriage;
	}

	public void setMarriage(String marriage) {
		this.marriage = marriage == null ? null : marriage.trim();
	}

	public String getProfessional() {
		return professional;
	}

	public void setProfessional(String professional) {
		this.professional = professional == null ? null : professional.trim();
	}

	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality == null ? null : nationality.trim();
	}

	public String getWorkUnit() {
		return workUnit;
	}

	public void setWorkUnit(String workUnit) {
		this.workUnit = workUnit == null ? null : workUnit.trim();
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	public String getNational() {
		return national;
	}

	public void setNational(String national) {
		this.national = national == null ? null : national.trim();
	}

	public String getCustStatus() {
		return custStatus;
	}

	public void setCustStatus(String custStatus) {
		this.custStatus = custStatus;
	}

	public String getCustType() {
		return custType;
	}

	public void setCustType(String custType) {
		this.custType = custType;
	}

	public Integer getSysCustId() {
		return sysCustId;
	}

	public void setSysCustId(Integer sysCustId) {
		this.sysCustId = sysCustId;
	}
}