package cn.ziroom.contract.domain;

public class RoomPictures implements java.io.Serializable {

	private static final long serialVersionUID = -2266510186494070740L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_room_pictures.hpimageid
	 * 
	 * @mbggenerated Thu Dec 15 12:36:35 CST 2011
	 */
	private Integer hpimageid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_room_pictures.room_code
	 * 
	 * @mbggenerated Thu Dec 15 12:36:35 CST 2011
	 */
	private String roomCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_room_pictures.image_name
	 * 
	 * @mbggenerated Thu Dec 15 12:36:35 CST 2011
	 */
	private String imageName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_room_pictures.imagetype
	 * 
	 * @mbggenerated Thu Dec 15 12:36:35 CST 2011
	 */
	private Integer imagetype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_room_pictures.imagepath
	 * 
	 * @mbggenerated Thu Dec 15 12:36:35 CST 2011
	 */
	private String imagepath;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_room_pictures.image_cate
	 * 
	 * @mbggenerated Thu Dec 15 12:36:35 CST 2011
	 */
	private String imageCate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_room_pictures.image_code
	 * 
	 * @mbggenerated Thu Dec 15 12:36:35 CST 2011
	 */
	private String imageCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_room_pictures.flag
	 * 
	 * @mbggenerated Thu Dec 15 12:36:35 CST 2011
	 */
	private String flag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_room_pictures.house_code
	 * 
	 * @mbggenerated Thu Dec 15 12:36:35 CST 2011
	 */
	private String houseCode;
	
	private Integer sysRoomId;
	private Integer sysHouseId;

	public Integer getHpimageid() {
		return hpimageid;
	}

	public void setHpimageid(Integer hpimageid) {
		this.hpimageid = hpimageid;
	}

	public String getRoomCode() {
		return roomCode;
	}

	public void setRoomCode(String roomCode) {
		this.roomCode = roomCode == null ? null : roomCode.trim();
	}

	public String getImageName() {
		return imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName == null ? null : imageName.trim();
	}

	public Integer getImagetype() {
		return imagetype;
	}

	public void setImagetype(Integer imagetype) {
		this.imagetype = imagetype;
	}

	public String getImagepath() {
		return imagepath;
	}

	public void setImagepath(String imagepath) {
		this.imagepath = imagepath == null ? null : imagepath.trim();
	}

	public String getImageCate() {
		return imageCate;
	}

	public void setImageCate(String imageCate) {
		this.imageCate = imageCate == null ? null : imageCate.trim();
	}

	public String getImageCode() {
		return imageCode;
	}

	public void setImageCode(String imageCode) {
		this.imageCode = imageCode == null ? null : imageCode.trim();
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag == null ? null : flag.trim();
	}

	public String getHouseCode() {
		return houseCode;
	}

	public void setHouseCode(String houseCode) {
		this.houseCode = houseCode == null ? null : houseCode.trim();
	}

	public Integer getSysRoomId() {
		return sysRoomId;
	}

	public void setSysRoomId(Integer sysRoomId) {
		this.sysRoomId = sysRoomId;
	}

	public Integer getSysHouseId() {
		return sysHouseId;
	}

	public void setSysHouseId(Integer sysHouseId) {
		this.sysHouseId = sysHouseId;
	}
}