package cn.ziroom.basic.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class Area implements java.io.Serializable {

	private static final long serialVersionUID = -3722814352736347632L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.housingprojectid
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private Integer housingprojectid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.projectcode
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String projectcode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.projectname
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String projectname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.projectalias
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String projectalias;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.projectpinyin
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String projectpinyin;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.projectjianpin
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String projectjianpin;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.fullviewpath
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String fullviewpath;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.longitude
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private Float longitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.latitude
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private Float latitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.propcompanyname
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String propcompanyname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.propcompany_type
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String propcompanyType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.propcompany_phone
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String propcompanyPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.propertyfee
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private Long propertyfee;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.ugplotnum
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private Long ugplotnum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.devcompanyname
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String devcompanyname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.completionyear
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String completionyear;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.totalarea
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private Integer totalarea;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.floorarearatio
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private BigDecimal floorarearatio;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.greenarearatio
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private BigDecimal greenarearatio;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.subway_info
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String subwayInfo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.subwaydistance
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String subwaydistance;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.subway_name
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String subwayName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.bus_code
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String busCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.address
	 * 
	 * @mbggenerated Fri Dec 02 17:05:17 CST 2011
	 */
	private String address;

	private String roadtransit;

	private String park;
	private String hospital;
	private String supermarket;
	private String market;
	private String entertainment;
	private String subwaystation;
	private String stationName;
	private String projectintroduce;
	private String cycleName;
	private String businessName;

	private String flag;
	/** 金融 */
	private List<AreaData> roadtransitList = new ArrayList<AreaData>();
	/** 公园 */
	private List<AreaData> parkList = new ArrayList<AreaData>();
	/** 医院 */
	private List<AreaData> hospitalList = new ArrayList<AreaData>();
	/** 超市 */
	private List<AreaData> supermarketList = new ArrayList<AreaData>();
	/** 市场 */
	private List<AreaData> marketList = new ArrayList<AreaData>();
	/** 娱乐 */
	private List<AreaData> entertainmentList = new ArrayList<AreaData>();
	/** 地铁站点 */
	private List<AreaData> subwaystationList = new ArrayList<AreaData>();
	/** 公交站点 */
	private List<AreaData> stationNameList = new ArrayList<AreaData>();

	public Integer getHousingprojectid() {
		return housingprojectid;
	}

	public void setHousingprojectid(Integer housingprojectid) {
		this.housingprojectid = housingprojectid;
	}

	public String getProjectcode() {
		return projectcode;
	}

	public void setProjectcode(String projectcode) {
		this.projectcode = projectcode == null ? null : projectcode.trim();
	}

	public String getProjectname() {
		return projectname;
	}

	public void setProjectname(String projectname) {
		this.projectname = projectname == null ? null : projectname.trim();
	}

	public String getProjectalias() {
		return projectalias;
	}

	public void setProjectalias(String projectalias) {
		this.projectalias = projectalias == null ? null : projectalias.trim();
	}

	public String getProjectpinyin() {
		return projectpinyin;
	}

	public void setProjectpinyin(String projectpinyin) {
		this.projectpinyin = projectpinyin == null ? null : projectpinyin.trim();
	}

	public String getProjectjianpin() {
		return projectjianpin;
	}

	public void setProjectjianpin(String projectjianpin) {
		this.projectjianpin = projectjianpin == null ? null : projectjianpin.trim();
	}

	public String getFullviewpath() {
		return fullviewpath;
	}

	public void setFullviewpath(String fullviewpath) {
		this.fullviewpath = fullviewpath == null ? null : fullviewpath.trim();
	}

	public Float getLongitude() {
		return longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public Float getLatitude() {
		return latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public String getPropcompanyname() {
		return propcompanyname;
	}

	public void setPropcompanyname(String propcompanyname) {
		this.propcompanyname = propcompanyname == null ? null : propcompanyname.trim();
	}

	public String getPropcompanyType() {
		return propcompanyType;
	}

	public void setPropcompanyType(String propcompanyType) {
		this.propcompanyType = propcompanyType == null ? null : propcompanyType.trim();
	}

	public String getPropcompanyPhone() {
		return propcompanyPhone;
	}

	public void setPropcompanyPhone(String propcompanyPhone) {
		this.propcompanyPhone = propcompanyPhone == null ? null : propcompanyPhone.trim();
	}

	public Long getPropertyfee() {
		return propertyfee;
	}

	public void setPropertyfee(Long propertyfee) {
		this.propertyfee = propertyfee;
	}

	public Long getUgplotnum() {
		return ugplotnum;
	}

	public void setUgplotnum(Long ugplotnum) {
		this.ugplotnum = ugplotnum;
	}

	public String getDevcompanyname() {
		return devcompanyname;
	}

	public void setDevcompanyname(String devcompanyname) {
		this.devcompanyname = devcompanyname == null ? null : devcompanyname.trim();
	}

	public String getCompletionyear() {
		return completionyear;
	}

	public void setCompletionyear(String completionyear) {
		this.completionyear = completionyear == null ? null : completionyear.trim();
	}

	public Integer getTotalarea() {
		return totalarea;
	}

	public void setTotalarea(Integer totalarea) {
		this.totalarea = totalarea;
	}

	public BigDecimal getFloorarearatio() {
		return floorarearatio;
	}

	public void setFloorarearatio(BigDecimal floorarearatio) {
		this.floorarearatio = floorarearatio;
	}

	public BigDecimal getGreenarearatio() {
		return greenarearatio;
	}

	public void setGreenarearatio(BigDecimal greenarearatio) {
		this.greenarearatio = greenarearatio;
	}

	public String getSubwayInfo() {
		return subwayInfo;
	}

	public void setSubwayInfo(String subwayInfo) {
		this.subwayInfo = subwayInfo == null ? null : subwayInfo.trim();
	}

	public String getSubwaydistance() {
		return subwaydistance;
	}

	public void setSubwaydistance(String subwaydistance) {
		this.subwaydistance = subwaydistance == null ? null : subwaydistance.trim();
	}

	public String getSubwayName() {
		return subwayName;
	}

	public void setSubwayName(String subwayName) {
		this.subwayName = subwayName == null ? null : subwayName.trim();
	}

	public String getBusCode() {
		return busCode;
	}

	public void setBusCode(String busCode) {
		this.busCode = busCode == null ? null : busCode.trim();
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	public String getRoadtransit() {
		return roadtransit;
	}

	public void setRoadtransit(String roadtransit) {
		this.roadtransit = roadtransit;
	}

	public String getPark() {
		return park;
	}

	public void setPark(String park) {
		this.park = park;
	}

	public String getHospital() {
		return hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}

	public String getSupermarket() {
		return supermarket;
	}

	public void setSupermarket(String supermarket) {
		this.supermarket = supermarket;
	}

	public String getMarket() {
		return market;
	}

	public void setMarket(String market) {
		this.market = market;
	}

	public String getEntertainment() {
		return entertainment;
	}

	public void setEntertainment(String entertainment) {
		this.entertainment = entertainment;
	}

	public String getSubwaystation() {
		return subwaystation;
	}

	public void setSubwaystation(String subwaystation) {
		this.subwaystation = subwaystation;
	}

	public String getStationName() {
		return stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public String getProjectintroduce() {
		return projectintroduce;
	}

	public void setProjectintroduce(String projectintroduce) {
		this.projectintroduce = projectintroduce;
	}

	public String getCycleName() {
		return cycleName;
	}

	public void setCycleName(String cycleName) {
		this.cycleName = cycleName;
	}

	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public List<AreaData> getRoadtransitList() {
		return roadtransitList;
	}

	public void setRoadtransitList(List<AreaData> roadtransitList) {
		this.roadtransitList = roadtransitList;
	}

	public List<AreaData> getParkList() {
		return parkList;
	}

	public void setParkList(List<AreaData> parkList) {
		this.parkList = parkList;
	}

	public List<AreaData> getHospitalList() {
		return hospitalList;
	}

	public void setHospitalList(List<AreaData> hospitalList) {
		this.hospitalList = hospitalList;
	}

	public List<AreaData> getSupermarketList() {
		return supermarketList;
	}

	public void setSupermarketList(List<AreaData> supermarketList) {
		this.supermarketList = supermarketList;
	}

	public List<AreaData> getMarketList() {
		return marketList;
	}

	public void setMarketList(List<AreaData> marketList) {
		this.marketList = marketList;
	}

	public List<AreaData> getEntertainmentList() {
		return entertainmentList;
	}

	public void setEntertainmentList(List<AreaData> entertainmentList) {
		this.entertainmentList = entertainmentList;
	}

	public List<AreaData> getSubwaystationList() {
		return subwaystationList;
	}

	public void setSubwaystationList(List<AreaData> subwaystationList) {
		this.subwaystationList = subwaystationList;
	}

	public List<AreaData> getStationNameList() {
		return stationNameList;
	}

	public void setStationNameList(List<AreaData> stationNameList) {
		this.stationNameList = stationNameList;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}