package cn.ziroom.basic.domain;

public class Business implements java.io.Serializable {

	private static final long serialVersionUID = 633497003740816417L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_business.business_id
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private Integer businessId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_business.business_name
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String businessName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_business.business_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String businessCode;
	
	private String flag;

	public Integer getBusinessId() {
		return businessId;
	}

	public void setBusinessId(Integer businessId) {
		this.businessId = businessId;
	}

	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName == null ? null : businessName.trim();
	}

	public String getBusinessCode() {
		return businessCode;
	}

	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode == null ? null : businessCode.trim();
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
}