package cn.ziroom.basic.domain;

public class CycleFace implements java.io.Serializable {

	private static final long serialVersionUID = 8981874410071726097L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cycle_face.id
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cycle_face.face_name
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String faceName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cycle_face.face_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String faceCode;
	
	private String flag;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFaceName() {
		return faceName;
	}

	public void setFaceName(String faceName) {
		this.faceName = faceName == null ? null : faceName.trim();
	}

	public String getFaceCode() {
		return faceCode;
	}

	public void setFaceCode(String faceCode) {
		this.faceCode = faceCode == null ? null : faceCode.trim();
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
}