package cn.ziroom.basic.domain;

public class Cycle implements java.io.Serializable {

	private static final long serialVersionUID = -8639380843870116647L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cycle.cycle_id
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private Integer cycleId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cycle.city_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String cityCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cycle.cycle_name
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String cycleName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_cycle.cycle_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String cycleCode;
	
	private String flag;

	public Integer getCycleId() {
		return cycleId;
	}

	public void setCycleId(Integer cycleId) {
		this.cycleId = cycleId;
	}

	public String getCityCode() {
		return cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode == null ? null : cityCode.trim();
	}

	public String getCycleName() {
		return cycleName;
	}

	public void setCycleName(String cycleName) {
		this.cycleName = cycleName == null ? null : cycleName.trim();
	}

	public String getCycleCode() {
		return cycleCode;
	}

	public void setCycleCode(String cycleCode) {
		this.cycleCode = cycleCode == null ? null : cycleCode.trim();
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
}