package cn.ziroom.basic.domain;

public class District implements java.io.Serializable {

	private static final long serialVersionUID = 8959698198989097942L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district.district_id
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private Integer districtId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district.city_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String cityCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district.district_name
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String districtName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district.district_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String districtCode;
	
	private String flag;

	public Integer getDistrictId() {
		return districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public String getCityCode() {
		return cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode == null ? null : cityCode.trim();
	}

	public String getDistrictName() {
		return districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName == null ? null : districtName.trim();
	}

	public String getDistrictCode() {
		return districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode == null ? null : districtCode.trim();
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
}