package cn.ziroom.basic.domain;

public class DistrictBusiness implements java.io.Serializable {

	private static final long serialVersionUID = 3424604128881982614L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district_business.id
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district_business.district_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String districtCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district_business.business_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String businessCode;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDistrictCode() {
		return districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode == null ? null : districtCode.trim();
	}

	public String getBusinessCode() {
		return businessCode;
	}

	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode == null ? null : businessCode.trim();
	}
}