package cn.ziroom.basic.domain;

public class SubStation implements java.io.Serializable {

	private static final long serialVersionUID = -5193734328370563197L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_sub_station.id
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_sub_station.subway_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String subwayCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_sub_station.station_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String stationCode;
	
	private String flag;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSubwayCode() {
		return subwayCode;
	}

	public void setSubwayCode(String subwayCode) {
		this.subwayCode = subwayCode == null ? null : subwayCode.trim();
	}

	public String getStationCode() {
		return stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode == null ? null : stationCode.trim();
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
}