package cn.ziroom.basic.domain;

public class SubwayStation implements java.io.Serializable {

	private static final long serialVersionUID = -2234712685051097195L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_subway_station.station_id
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private Integer stationId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_subway_station.station_name
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String stationName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_subway_station.station_code
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private String stationCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_subway_station.longitude
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private Float longitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_subway_station.latitude
	 * 
	 * @mbggenerated Thu Dec 01 14:59:57 CST 2011
	 */
	private Float latitude;
	
	private String flag;

	public Integer getStationId() {
		return stationId;
	}

	public void setStationId(Integer stationId) {
		this.stationId = stationId;
	}

	public String getStationName() {
		return stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName == null ? null : stationName.trim();
	}

	public String getStationCode() {
		return stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode == null ? null : stationCode.trim();
	}

	public Float getLongitude() {
		return longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public Float getLatitude() {
		return latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
}