package cn.ziroom.house.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import cn.common.service.GeneralCriteria;

/**
 * 房屋实体类
 * 
 * @author Administrator
 * 
 */
public class House extends GeneralCriteria {

	private static final long serialVersionUID = 1587735686113156326L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.house_id
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer houseId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.title
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.house_code
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String houseCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.dict_house_code
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String dictHouseCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.province
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String province;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.city
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String city;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.cycle
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String cycle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.cycle_face
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String cycleFace;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.counties
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String counties;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.shopping
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String shopping;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.subway_stations
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String subwayStations;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.subway_line
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String subwayLine;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.projectcode
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String projectcode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.building
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String building;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.unit
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String unit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.floor
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String floor;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.total_floor
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String totalFloor;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.house_number
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String houseNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.build_type
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String buildType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.original_build_type
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String originalBuildType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.house_face
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String houseFace;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.house_area
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String houseArea;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.heating
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String heating;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.decorate_living_num
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer decorateLivingNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.decorate_bedroom_num
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer decorateBedroomNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.decorate_kitchen_num
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer decorateKitchenNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.decorate_bathroom_num
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer decorateBathroomNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.decorate_balcony
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer decorateBalcony;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.decorate_garden
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer decorateGarden;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.decorate_gazebo
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer decorateGazebo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.payment
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Long payment;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.rent_num
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer rentNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.house_evaluate
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String houseEvaluate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.environment_evaluate
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String environmentEvaluate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.rent_type
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String rentType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.assistant_code
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer assistantCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.agent_phone
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String agentPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.agent_name
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String agentName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.steward_code
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String stewardCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.steward_name
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String stewardName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.steward_phone
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String stewardPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.leader_code
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String leaderCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.broadband
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String broadband;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.ladder
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer ladder;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.household
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Integer household;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.house_product
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String houseProduct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.customer_pay
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String customerPay;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.check_in_time
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private Date checkInTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.flv_url
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String flvUrl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.is_top
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String isTop;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.is_available
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String isAvailable;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.is_promotions
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String isPromotions;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.is_show
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String isShow;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.house_status
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String houseStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.rent_status
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String rentStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.flag
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String flag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_house.characteristics
	 * 
	 * @mbggenerated Fri Dec 16 12:55:59 CST 2011
	 */
	private String characteristics;

	private String ckd;

	private String departName;

	private List<Room> roomList = new ArrayList<Room>();

	private String areaName;

	private String staffid;
	
	private Integer sysHouseId;
    private Integer sysContractId;
    
    private String dep1;
    private String dep2;
    private String r1;
    private String r2;

	public Integer getHouseId() {
		return houseId;
	}

	public void setHouseId(Integer houseId) {
		this.houseId = houseId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	public String getHouseCode() {
		return houseCode;
	}

	public void setHouseCode(String houseCode) {
		this.houseCode = houseCode == null ? null : houseCode.trim();
	}

	public String getDictHouseCode() {
		return dictHouseCode;
	}

	public void setDictHouseCode(String dictHouseCode) {
		this.dictHouseCode = dictHouseCode == null ? null : dictHouseCode.trim();
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	public String getCycle() {
		return cycle;
	}

	public void setCycle(String cycle) {
		this.cycle = cycle == null ? null : cycle.trim();
	}

	public String getCycleFace() {
		return cycleFace;
	}

	public void setCycleFace(String cycleFace) {
		this.cycleFace = cycleFace == null ? null : cycleFace.trim();
	}

	public String getCounties() {
		return counties;
	}

	public void setCounties(String counties) {
		this.counties = counties == null ? null : counties.trim();
	}

	public String getShopping() {
		return shopping;
	}

	public void setShopping(String shopping) {
		this.shopping = shopping == null ? null : shopping.trim();
	}

	public String getSubwayStations() {
		return subwayStations;
	}

	public void setSubwayStations(String subwayStations) {
		this.subwayStations = subwayStations == null ? null : subwayStations.trim();
	}

	public String getSubwayLine() {
		return subwayLine;
	}

	public void setSubwayLine(String subwayLine) {
		this.subwayLine = subwayLine == null ? null : subwayLine.trim();
	}

	public String getProjectcode() {
		return projectcode;
	}

	public void setProjectcode(String projectcode) {
		this.projectcode = projectcode == null ? null : projectcode.trim();
	}

	public String getBuilding() {
		return building;
	}

	public void setBuilding(String building) {
		this.building = building == null ? null : building.trim();
	}

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	public String getFloor() {
		return floor;
	}

	public void setFloor(String floor) {
		this.floor = floor == null ? null : floor.trim();
	}

	public String getTotalFloor() {
		return totalFloor;
	}

	public void setTotalFloor(String totalFloor) {
		this.totalFloor = totalFloor == null ? null : totalFloor.trim();
	}

	public String getHouseNumber() {
		return houseNumber;
	}

	public void setHouseNumber(String houseNumber) {
		this.houseNumber = houseNumber == null ? null : houseNumber.trim();
	}

	public String getBuildType() {
		return buildType;
	}

	public void setBuildType(String buildType) {
		this.buildType = buildType == null ? null : buildType.trim();
	}

	public String getOriginalBuildType() {
		return originalBuildType;
	}

	public void setOriginalBuildType(String originalBuildType) {
		this.originalBuildType = originalBuildType == null ? null : originalBuildType.trim();
	}

	public String getHouseFace() {
		return houseFace;
	}

	public void setHouseFace(String houseFace) {
		this.houseFace = houseFace == null ? null : houseFace.trim();
	}

	public String getHouseArea() {
		return houseArea;
	}

	public void setHouseArea(String houseArea) {
		this.houseArea = houseArea == null ? null : houseArea.trim();
	}

	public String getHeating() {
		return heating;
	}

	public void setHeating(String heating) {
		this.heating = heating == null ? null : heating.trim();
	}

	public Integer getDecorateLivingNum() {
		return decorateLivingNum;
	}

	public void setDecorateLivingNum(Integer decorateLivingNum) {
		this.decorateLivingNum = decorateLivingNum;
	}

	public Integer getDecorateBedroomNum() {
		return decorateBedroomNum;
	}

	public void setDecorateBedroomNum(Integer decorateBedroomNum) {
		this.decorateBedroomNum = decorateBedroomNum;
	}

	public Integer getDecorateKitchenNum() {
		return decorateKitchenNum;
	}

	public void setDecorateKitchenNum(Integer decorateKitchenNum) {
		this.decorateKitchenNum = decorateKitchenNum;
	}

	public Integer getDecorateBathroomNum() {
		return decorateBathroomNum;
	}

	public void setDecorateBathroomNum(Integer decorateBathroomNum) {
		this.decorateBathroomNum = decorateBathroomNum;
	}

	public Integer getDecorateBalcony() {
		return decorateBalcony;
	}

	public void setDecorateBalcony(Integer decorateBalcony) {
		this.decorateBalcony = decorateBalcony;
	}

	public Integer getDecorateGarden() {
		return decorateGarden;
	}

	public void setDecorateGarden(Integer decorateGarden) {
		this.decorateGarden = decorateGarden;
	}

	public Integer getDecorateGazebo() {
		return decorateGazebo;
	}

	public void setDecorateGazebo(Integer decorateGazebo) {
		this.decorateGazebo = decorateGazebo;
	}

	public Long getPayment() {
		return payment;
	}

	public void setPayment(Long payment) {
		this.payment = payment;
	}

	public Integer getRentNum() {
		return rentNum;
	}

	public void setRentNum(Integer rentNum) {
		this.rentNum = rentNum;
	}

	public String getHouseEvaluate() {
		return houseEvaluate;
	}

	public void setHouseEvaluate(String houseEvaluate) {
		this.houseEvaluate = houseEvaluate == null ? null : houseEvaluate.trim();
	}

	public String getEnvironmentEvaluate() {
		return environmentEvaluate;
	}

	public void setEnvironmentEvaluate(String environmentEvaluate) {
		this.environmentEvaluate = environmentEvaluate == null ? null : environmentEvaluate.trim();
	}

	public String getRentType() {
		return rentType;
	}

	public void setRentType(String rentType) {
		this.rentType = rentType == null ? null : rentType.trim();
	}

	public Integer getAssistantCode() {
		return assistantCode;
	}

	public void setAssistantCode(Integer assistantCode) {
		this.assistantCode = assistantCode;
	}

	public String getAgentPhone() {
		return agentPhone;
	}

	public void setAgentPhone(String agentPhone) {
		this.agentPhone = agentPhone == null ? null : agentPhone.trim();
	}

	public String getAgentName() {
		return agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName == null ? null : agentName.trim();
	}

	public String getStewardCode() {
		return stewardCode;
	}

	public void setStewardCode(String stewardCode) {
		this.stewardCode = stewardCode == null ? null : stewardCode.trim();
	}

	public String getStewardName() {
		return stewardName;
	}

	public void setStewardName(String stewardName) {
		this.stewardName = stewardName == null ? null : stewardName.trim();
	}

	public String getStewardPhone() {
		return stewardPhone;
	}

	public void setStewardPhone(String stewardPhone) {
		this.stewardPhone = stewardPhone == null ? null : stewardPhone.trim();
	}

	public String getLeaderCode() {
		return leaderCode;
	}

	public void setLeaderCode(String leaderCode) {
		this.leaderCode = leaderCode == null ? null : leaderCode.trim();
	}

	public String getBroadband() {
		return broadband;
	}

	public void setBroadband(String broadband) {
		this.broadband = broadband == null ? null : broadband.trim();
	}

	public Integer getLadder() {
		return ladder;
	}

	public void setLadder(Integer ladder) {
		this.ladder = ladder;
	}

	public Integer getHousehold() {
		return household;
	}

	public void setHousehold(Integer household) {
		this.household = household;
	}

	public String getHouseProduct() {
		return houseProduct;
	}

	public void setHouseProduct(String houseProduct) {
		this.houseProduct = houseProduct == null ? null : houseProduct.trim();
	}

	public String getCustomerPay() {
		return customerPay;
	}

	public void setCustomerPay(String customerPay) {
		this.customerPay = customerPay == null ? null : customerPay.trim();
	}

	public Date getCheckInTime() {
		return checkInTime;
	}

	public void setCheckInTime(Date checkInTime) {
		this.checkInTime = checkInTime;
	}

	public String getFlvUrl() {
		return flvUrl;
	}

	public void setFlvUrl(String flvUrl) {
		this.flvUrl = flvUrl == null ? null : flvUrl.trim();
	}

	public String getIsTop() {
		return isTop;
	}

	public void setIsTop(String isTop) {
		this.isTop = isTop == null ? null : isTop.trim();
	}

	public String getIsAvailable() {
		return isAvailable;
	}

	public void setIsAvailable(String isAvailable) {
		this.isAvailable = isAvailable == null ? null : isAvailable.trim();
	}

	public String getIsPromotions() {
		return isPromotions;
	}

	public void setIsPromotions(String isPromotions) {
		this.isPromotions = isPromotions == null ? null : isPromotions.trim();
	}

	public String getIsShow() {
		return isShow;
	}

	public void setIsShow(String isShow) {
		this.isShow = isShow == null ? null : isShow.trim();
	}

	public String getHouseStatus() {
		return houseStatus;
	}

	public void setHouseStatus(String houseStatus) {
		this.houseStatus = houseStatus == null ? null : houseStatus.trim();
	}

	public String getRentStatus() {
		return rentStatus;
	}

	public void setRentStatus(String rentStatus) {
		this.rentStatus = rentStatus == null ? null : rentStatus.trim();
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag == null ? null : flag.trim();
	}

	public String getCharacteristics() {
		return characteristics;
	}

	public void setCharacteristics(String characteristics) {
		this.characteristics = characteristics == null ? null : characteristics.trim();
	}

	public List<Room> getRoomList() {
		return roomList;
	}

	public void setRoomList(List<Room> roomList) {
		this.roomList = roomList;
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public String getCkd() {
		return ckd;
	}

	public void setCkd(String ckd) {
		this.ckd = ckd;
	}

	public String getDepartName() {
		return departName;
	}

	public void setDepartName(String departName) {
		this.departName = departName;
	}

	public String getStaffid() {
		return staffid;
	}

	public void setStaffid(String staffid) {
		this.staffid = staffid;
	}

	public Integer getSysHouseId() {
		return sysHouseId;
	}

	public void setSysHouseId(Integer sysHouseId) {
		this.sysHouseId = sysHouseId;
	}

	public Integer getSysContractId() {
		return sysContractId;
	}

	public void setSysContractId(Integer sysContractId) {
		this.sysContractId = sysContractId;
	}

	public String getDep1() {
		return dep1;
	}

	public void setDep1(String dep1) {
		this.dep1 = dep1;
	}

	public String getDep2() {
		return dep2;
	}

	public void setDep2(String dep2) {
		this.dep2 = dep2;
	}

	public String getR1() {
		return r1;
	}

	public void setR1(String r1) {
		this.r1 = r1;
	}

	public String getR2() {
		return r2;
	}

	public void setR2(String r2) {
		this.r2 = r2;
	}
}